name: Build Installers

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allow manual triggering

env:
  CARGO_TERM_COLOR: always

jobs:
  build-installers:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: ''
            target: 'aarch64-apple-darwin'
            name: 'macOS (Apple Silicon)'
            artifact: 'macos-aarch64'
          - platform: 'macos-latest' 
            args: '--target x86_64-apple-darwin'
            target: 'x86_64-apple-darwin'
            name: 'macOS (Intel)'
            artifact: 'macos-x86_64'
          - platform: 'windows-latest'
            args: ''
            target: 'x86_64-pc-windows-msvc'
            name: 'Windows (x64)'
            artifact: 'windows-x64'

    runs-on: ${{ matrix.platform }}
    name: Build ${{ matrix.name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install frontend dependencies
        run: npm ci

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}
          workspaces: src-tauri

      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install Windows dependencies
        if: matrix.platform == 'windows-latest'
        run: |
          # Windows WebView2 is usually pre-installed, but let's ensure it
          echo "Windows build environment ready"

      - name: Debug build environment
        run: |
          echo "Platform: ${{ matrix.platform }}"
          echo "Target: ${{ matrix.target }}"
          echo "Args: ${{ matrix.args }}"
          rustc --version
          cargo --version

      - name: Build application
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ${{ matrix.args }}
          includeDebug: false
          includeRelease: true

      - name: Debug build outputs
        run: |
          echo "=== Searching for build outputs ==="
          find src-tauri/target -name "*.dmg" -o -name "*.exe" -o -name "*.msi" -o -name "*.app" 2>/dev/null || echo "No installer files found"
          echo "=== Target directory structure ==="
          ls -la src-tauri/target/ 2>/dev/null || echo "No target directory"
          echo "=== Bundle directories ==="
          find src-tauri/target -name "bundle" -type d 2>/dev/null || echo "No bundle directories"
        shell: bash

      - name: Upload macOS artifacts
        if: matrix.platform == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: |
            src-tauri/target/**/bundle/dmg/*.dmg
            src-tauri/target/**/bundle/macos/*.app
          if-no-files-found: warn
          retention-days: 30

      - name: Upload Windows artifacts
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: |
            src-tauri/target/**/bundle/nsis/*.exe
            src-tauri/target/**/bundle/msi/*.msi
          if-no-files-found: warn
          retention-days: 30

      - name: Upload any bundle artifacts (fallback)
        uses: actions/upload-artifact@v4
        with:
          name: debug-${{ matrix.artifact }}
          path: |
            src-tauri/target/**/bundle/**/*
          if-no-files-found: ignore
          retention-days: 7

  create-release:
    needs: build-installers
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Display structure of downloaded files
        run: |
          echo "=== Downloaded artifacts ==="
          find ./artifacts -type f -name "*.dmg" -o -name "*.exe" -o -name "*.msi" -o -name "*.app" | sort
          echo "=== Full directory structure ==="
          ls -la ./artifacts/

      - name: Prepare release files
        run: |
          mkdir -p ./release-files
          find ./artifacts -name "*.dmg" -exec cp {} ./release-files/ \;
          find ./artifacts -name "*.exe" -exec cp {} ./release-files/ \;
          find ./artifacts -name "*.msi" -exec cp {} ./release-files/ \;
          echo "=== Release files prepared ==="
          ls -la ./release-files/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./release-files/*
          draft: false
          prerelease: false
          generate_release_notes: true
          fail_on_unmatched_files: false
          body: |
            ## 🎉 Optics Ring Generator Professional

            ### Download Installers:
            
            **macOS:**
            - Apple Silicon (M1/M2/M3): `*_aarch64.dmg`
            - Intel: `*_x86_64.dmg`
            - Universal (Both): `*_universal.dmg`
            
            **Windows:**
            - Windows 10/11 (64-bit): `*.exe` or `*.msi`
            
            ### Installation:
            - **macOS**: Double-click DMG, drag to Applications
            - **Windows**: Run the EXE installer as administrator
            
            ### Features:
            - ✅ Professional 3D ring generator
            - ✅ Three ring types (Convex, Concave, Three-Point)
            - ✅ Real-time 3D preview
            - ✅ STL export for 3D printing
            - ✅ All dependencies included
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-universal-macos:
    runs-on: macos-latest
    name: Build macOS Universal Binary
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install frontend dependencies
        run: npm ci

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin,x86_64-apple-darwin

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: universal-apple-darwin
          workspaces: src-tauri

      - name: Build Universal Binary
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --target universal-apple-darwin
          includeDebug: false
          includeRelease: true

      - name: Upload Universal macOS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-universal
          path: |
            src-tauri/target/*/release/bundle/dmg/*.dmg
            src-tauri/target/*/release/bundle/macos/*.app
          if-no-files-found: warn
          retention-days: 30
