name: Build Windows Installer

on:
  workflow_dispatch: # Manual trigger only
    inputs:
      version:
        description: 'Version tag (e.g., v1.0.0)'
        required: false
        default: 'latest'

jobs:
  build-windows:
    runs-on: windows-latest
    name: Build Windows Installer

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install frontend dependencies
        run: npm ci

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri

      - name: Check Windows build environment
        run: |
          echo "=== Environment Check ==="
          rustc --version
          cargo --version
          node --version
          npm --version
          echo "=== WebView2 Check ==="
          Get-WmiObject -Class Win32_Product | Where-Object {$_.Name -like "*WebView2*"} | Select-Object Name, Version

      - name: Try direct Tauri build
        run: |
          echo "=== Building with Tauri CLI directly ==="
          cd src-tauri
          cargo tauri build --verbose
        continue-on-error: true

      - name: Alternative: Build with tauri-action
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ''
        continue-on-error: true

      - name: List ALL build outputs
        run: |
          echo "=== All files in target directory ==="
          Get-ChildItem -Recurse src-tauri\target -ErrorAction SilentlyContinue | Where-Object {$_.Extension -match "\.(exe|msi|dmg)$"} | Format-Table FullName, Length
          echo "=== Bundle directories ==="
          Get-ChildItem -Recurse src-tauri\target -Name "*bundle*" -ErrorAction SilentlyContinue
          echo "=== Release directories ==="
          Get-ChildItem -Path "src-tauri\target" -Recurse -Directory -Name "*release*" -ErrorAction SilentlyContinue

      - name: Upload Windows installer (any location)
        uses: actions/upload-artifact@v4
        with:
          name: windows-debug-full
          path: |
            src-tauri/target/**/*.exe
            src-tauri/target/**/*.msi
          if-no-files-found: warn
          retention-days: 7

      - name: Create summary
        run: |
          echo "## 🔧 Windows Build Debug Results" >> $env:GITHUB_STEP_SUMMARY
          echo "" >> $env:GITHUB_STEP_SUMMARY
          echo "This workflow attempts to build the Windows installer and debug any issues." >> $env:GITHUB_STEP_SUMMARY
          echo "" >> $env:GITHUB_STEP_SUMMARY
          echo "### Check the logs above for:" >> $env:GITHUB_STEP_SUMMARY
          echo "1. Rust compilation errors" >> $env:GITHUB_STEP_SUMMARY
          echo "2. Tauri bundling issues" >> $env:GITHUB_STEP_SUMMARY
          echo "3. Missing dependencies" >> $env:GITHUB_STEP_SUMMARY
          echo "4. WebView2 availability" >> $env:GITHUB_STEP_SUMMARY
